spring.application.name=email-writer-sb
spring.jmx.enabled=true
gemini.api.url=${GEMINI_API_URL:http://localhost:8080}
gemini.api.key=${GEMINI_API_KEY:dummy}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME:}
spring.mail.password=${GMAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.test-connection=false
